# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'PantryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.7'

  # Pods for PantryApp

end
